// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxuFNYTDKPMbo7w5t1hGPk61ZW1kXKioY',
    appId: '1:174749190262:web:eb81f2e40618e8f4603757',
    messagingSenderId: '174749190262',
    projectId: 'wis-permission-system',
    authDomain: 'wis-permission-system.firebaseapp.com',
    storageBucket: 'wis-permission-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdOCfAXVaMGVnhG5MGUcmbnUUs0NZBMc',
    appId: '1:174749190262:android:55e68e6e1b64e811603757',
    messagingSenderId: '174749190262',
    projectId: 'wis-permission-system',
    storageBucket: 'wis-permission-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBUfrLX5vL7Pg4Apk4330Aq07OuvDGxs',
    appId: '1:174749190262:ios:49a14abc9475ad5d603757',
    messagingSenderId: '174749190262',
    projectId: 'wis-permission-system',
    storageBucket: 'wis-permission-system.firebasestorage.app',
    iosBundleId: 'com.example.permissionSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBUfrLX5vL7Pg4Apk4330Aq07OuvDGxs',
    appId: '1:174749190262:ios:49a14abc9475ad5d603757',
    messagingSenderId: '174749190262',
    projectId: 'wis-permission-system',
    storageBucket: 'wis-permission-system.firebasestorage.app',
    iosBundleId: 'com.example.permissionSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxuFNYTDKPMbo7w5t1hGPk61ZW1kXKioY',
    appId: '1:174749190262:web:0797d0e79697ff9e603757',
    messagingSenderId: '174749190262',
    projectId: 'wis-permission-system',
    authDomain: 'wis-permission-system.firebaseapp.com',
    storageBucket: 'wis-permission-system.firebasestorage.app',
  );

}